/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedCvRouteImport } from './routes/_authenticated/cv'
import { Route as AuthenticatedCvReviewRouteImport } from './routes/_authenticated/cv-review'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRepositoriesRouteImport } from './routes/_authenticated/repositories'
import { Route as ApiPublicGithubCallbackRouteImport } from './routes/api/public/github/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCvRoute = AuthenticatedCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCvReviewRoute = AuthenticatedCvReviewRouteImport.update({
  id: '/cv-review',
  path: '/cv-review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepositoriesRoute =
  AuthenticatedRepositoriesRouteImport.update({
    id: '/repositories',
    path: '/repositories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicGithubCallbackRoute = ApiPublicGithubCallbackRouteImport.update({
  id: '/api/public/github/callback',
  path: '/api/public/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/cv': typeof AuthenticatedCvRoute
  '/cv-review': typeof AuthenticatedCvReviewRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/repositories': typeof AuthenticatedRepositoriesRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/cv': typeof AuthenticatedCvRoute
  '/cv-review': typeof AuthenticatedCvReviewRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/repositories': typeof AuthenticatedRepositoriesRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/cv': typeof AuthenticatedCvRoute
  '/_authenticated/cv-review': typeof AuthenticatedCvReviewRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/repositories': typeof AuthenticatedRepositoriesRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/achievements'
    | '/cv'
    | '/cv-review'
    | '/dashboard'
    | '/repositories'
    | '/api/public/github/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/achievements'
    | '/cv'
    | '/cv-review'
    | '/dashboard'
    | '/repositories'
    | '/api/public/github/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/achievements'
    | '/_authenticated/cv'
    | '/_authenticated/cv-review'
    | '/_authenticated/dashboard'
    | '/_authenticated/repositories'
    | '/api/public/github/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicGithubCallbackRoute: typeof ApiPublicGithubCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cv': {
      id: '/_authenticated/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof AuthenticatedCvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cv-review': {
      id: '/_authenticated/cv-review'
      path: '/cv-review'
      fullPath: '/cv-review'
      preLoaderRoute: typeof AuthenticatedCvReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repositories': {
      id: '/_authenticated/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof AuthenticatedRepositoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/github/callback': {
      id: '/api/public/github/callback'
      path: '/api/public/github/callback'
      fullPath: '/api/public/github/callback'
      preLoaderRoute: typeof ApiPublicGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedCvRoute: typeof AuthenticatedCvRoute
  AuthenticatedCvReviewRoute: typeof AuthenticatedCvReviewRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRepositoriesRoute: typeof AuthenticatedRepositoriesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedCvRoute: AuthenticatedCvRoute,
  AuthenticatedCvReviewRoute: AuthenticatedCvReviewRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRepositoriesRoute: AuthenticatedRepositoriesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicGithubCallbackRoute: ApiPublicGithubCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
